Hybfs: DbBackend Class Reference
DbBackend Class Reference
#include <db_backend.hpp>
Public Member Functions
DbBackend (const char *path)
~DbBackend ()
int db_init_storage ()
void db_close_storage ()
int db_add_file_info (vector< string > *tags, file_info_t *finfo)
int db_delete_allfile_info (char *tag)
int db_delete_file_info (char *abspath)
int db_delete_file_tag (char *tag)
int db_check_tag (const char *tag, const char *value)
list< string > * db_get_tags_values ()
list< string > * db_get_tags ()
int db_get_files (const char *path, const char *tag, const char *value, void *buf, filler_t filler)
int db_get_filesinfo (list< string > *tags, string *path, void *buf, filler_t filler)
Private Member Functions
int run_simple_query (const char *query)
int create_main_tables ()
int db_add_tag (const char *tag, const char *value)
int db_add_file (file_info_t *finfo)
Private Attributes
string db_path
sqlite3 * db
Detailed Description
Definition at line 50 of file db_backend.hpp.
Constructor & Destructor Documentation
DbBackend::DbBackend (const char * path)
Definition at line 41 of file db_backend.cpp.
References db, and db_path.
DbBackend::~DbBackend ()
Definition at line 49 of file db_backend.cpp.
References db_close_storage().
Member Function Documentation
int DbBackend::run_simple_query (const char * query) [private]
wrapper for running a query. This is mostly used for creating tables.
Definition at line 73 of file db_backend.cpp.
References db, and DB_PRINTERR.
Referenced by create_main_tables().
int DbBackend::create_main_tables () [private]
Creates initial tables for the given database
Definition at line 98 of file db_backend.cpp.
References db, DB_ERROR, DB_PRINTERR, DBG_PRINT, and run_simple_query().
Referenced by db_init_storage().
int DbBackend::db_add_tag (const char * tag, const char * value) [private]
Adds a pair (tag,value) to the "tags" table. Returns the associated unique number. It does not replace the value for an existing tag. For internal use only.
Definition at line 192 of file db_backend.cpp.
References db, db_check_tag(), DB_PRINTERR, DBG_SHOWFC, and NULL_VALUE.
Referenced by db_add_file_info().
int DbBackend::db_add_file (file_info_t * finfo) [private]
Adds the information about a file to the database. It does not replace current info. It returns 0 for succes. Note that in the case of a duplicate ino it returns error.
Definition at line 241 of file db_backend.cpp.
References db, DB_PRINTERR, DBG_SHOWFC, file_info_t::fid, file_info_t::mode, file_info_t::name, and file_info_t::namelen.
Referenced by db_add_file_info().
int DbBackend::db_init_storage ()
Initialize database: create initial database file and tables in the desired branch, if they don't exist.
Definition at line 167 of file db_backend.cpp.
References create_main_tables(), db, db_close_storage(), db_path, DB_PRINTERR, DBG_PRINT, and DBG_SHOWFC.
Referenced by VirtualDirectory::init().
void DbBackend::db_close_storage ()
Close all the databases here
Definition at line 57 of file db_backend.cpp.
References db, DB_PRINTERR, and DBG_SHOWFC.
Referenced by db_init_storage(), and ~DbBackend().
int DbBackend::db_add_file_info (vector< string > * tags, file_info_t * finfo)
Adds the file information for a list of tags in the main db.
Definition at line 277 of file db_backend.cpp.
References db, db_add_file(), db_add_tag(), DB_PRINTERR, DBG_SHOWFC, and file_info_t::fid.
Referenced by VirtualDirectory::vdir_add_tag().
int DbBackend::db_delete_allfile_info (char * tag)
Deletes all the records from the main DB, coresponding to the key "tag"
Definition at line 360 of file db_backend.cpp.
int DbBackend::db_delete_file_info (char * abspath)
Deletes the record with the absolute path "abspath"
Definition at line 353 of file db_backend.cpp.
int DbBackend::db_delete_file_tag (char * tag)
Deletes all the information related to this tag
Definition at line 344 of file db_backend.cpp.
int DbBackend::db_check_tag (const char * tag, const char * value)
Checks if the tag is really a key in the main DB. Returns the tag id if it exists, 0 otherwise. In case of error, returns -1.
Definition at line 369 of file db_backend.cpp.
References db, DB_PRINTERR, DBG_PRINT, DBG_SHOWFC, and NULL_VALUE.
Referenced by db_add_tag().
list< string > * DbBackend::db_get_tags_values ()
Returns all tag-value pairs from the database
Definition at line 496 of file db_backend.cpp.
References db, DBG_SHOWFC, PRINT_ERROR, and tags_values_callback().
Referenced by VirtualDirectory::vdir_list_root().
list< string > * DbBackend::db_get_tags ()
Returns all tags from the database
Definition at line 447 of file db_backend.cpp.
References db, DBG_SHOWFC, PRINT_ERROR, and tags_callback().
Referenced by VirtualDirectory::vdir_list_root().
int DbBackend::db_get_files (const char * path, const char * tag, const char * value, void * buf, filler_t filler)
Returns the file information for the tag and the specified value. If the value is null than it returns all the files that have that tag. If the path is specified, it will try to do a match with the real path from the database.
Definition at line 534 of file db_backend.cpp.
References db, DB_PRINTERR, and DBG_PRINT.
Referenced by db_get_filesinfo().
int DbBackend::db_get_filesinfo (list< string > * tags, string * path, void * buf, filler_t filler)
Definition at line 521 of file db_backend.cpp.
References break_tag(), db_get_files(), and DBG_PRINT.
Referenced by VirtualDirectory::vdir_readdir().
Member Data Documentation
string DbBackend::db_path [private]
path to the database
Definition at line 77 of file db_backend.hpp.
Referenced by db_init_storage(), and DbBackend().
sqlite3* DbBackend::db [private]
handle to the database
Definition at line 81 of file db_backend.hpp.
Referenced by create_main_tables(), db_add_file(), db_add_file_info(), db_add_tag(), db_check_tag(), db_close_storage(), db_get_files(), db_get_tags(), db_get_tags_values(), db_init_storage(), DbBackend(), and run_simple_query().
The documentation for this class was generated from the following files:
include/db_backend.hpp
hybfs-core/db_backend.cpp