Hybfs: hybfs-core/hybfs.cpp File Reference
hybfs-core/hybfs.cpp File Reference
#include <sys/types.h>
#include <stdlib.h>
#include <unistd.h>
#include "hybfs.h"
#include "hybfsdef.h"
#include "misc.h"
Defines
#define ADD_FUSE_OPT(p)
#define INIT_KEY(index, string, key)
Functions
static void print_usage ()
int hybfs_opts (void *data, const char *arg, int key, struct fuse_args *outargs)
int main (int argc, char *argv[])
Define Documentation
#define ADD_FUSE_OPT (p)
Value:
if (fuse_opt_add_arg(&args, p)) { \
                fprintf(stderr, "Can't add %s to the list of options, aborting!\n",p); \
                return 1; \
        }
Definition at line 34 of file hybfs.cpp.
Referenced by main().
#define INIT_KEY (index, string, key)
Value:
options[index].templ = string; \
        options[index].offset = -1U; \
        options[index].value = key; \
Definition at line 77 of file hybfs.cpp.
Referenced by main().
Function Documentation
int hybfs_opts (void * data, const char * arg, int key, struct fuse_args * outargs)
Definition at line 49 of file hybfs.cpp.
References DBG_PRINT, HybfsData::doexit, KEY_HELP, HybfsData::parse_branches(), print_usage(), and HybfsData::retval.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 82 of file hybfs.cpp.
References ADD_FUSE_OPT, hybfs_access(), hybfs_getattr(), hybfs_opts(), hybfs_readdir(), hybfs_rename(), hybfs_unlink(), INIT_KEY, and KEY_HELP.
static void print_usage () [static]
Definition at line 40 of file hybfs.cpp.
Referenced by hybfs_opts().