Hybfs: include/misc.h File Reference
include/misc.h File Reference
#include <string>
#include "hybfs_data.hpp"
Defines
#define HAS_PATH 0x00000001
#define HAS_FILE 0x00000002
#define HAS_TAG 0x00000004
Functions
std::string * make_absolute (const char *relpath)
std::string * resolve_path (HybfsData *hybfs_core, const char *path, int *brid)
void break_tag (std::string *tag_value, std::string *tag, std::string *value)
Define Documentation
#define HAS_FILE 0x00000002
Definition at line 24 of file misc.h.
#define HAS_PATH 0x00000001
Definition at line 23 of file misc.h.
Referenced by hybfs_access().
#define HAS_TAG 0x00000004
Definition at line 25 of file misc.h.
Function Documentation
void break_tag (std::string * tag_value, std::string * tag, std::string * value)
Definition at line 72 of file misc.cpp.
Referenced by DbBackend::db_get_filesinfo().
std::string* make_absolute (const char * relpath)
Definition at line 21 of file misc.cpp.
References ABORT, DBG_PRINT, and PATHLEN_MAX.
Referenced by HybfsData::add_branch().
std::string* resolve_path (HybfsData * hybfs_core, const char * path, int * brid)
Definition at line 54 of file misc.cpp.
References HybfsData::get_branch_path().
Referenced by hybfs_access(), hybfs_getattr(), hybfs_readdir(), hybfs_unlink(), normal_getattr(), normal_rename(), and HybfsData::virtual_addtag().