Hybfs: PathCrawler Class Reference
PathCrawler Class Reference
#include <path_crawler.hpp>
Public Member Functions
PathCrawler (const char *_path)
PathCrawler (const char *_path, char _sep)
~PathCrawler ()
string get_rel_path ()
string get_first_path ()
int is_real ()
string get_next ()
int has_next ()
int break_queries ()
string pop_next_query ()
int has_next_query ()
Private Attributes
string path
size_t found
string last
string rest
char sep
string rel_path
string first_path
list< string > components
Detailed Description
Definition at line 22 of file path_crawler.hpp.
Constructor & Destructor Documentation
PathCrawler::PathCrawler (const char * _path)
Definition at line 15 of file path_crawler.cpp.
References found, path, rest, and sep.
PathCrawler::PathCrawler (const char * _path, char _sep)
Definition at line 24 of file path_crawler.cpp.
References found, path, rest, and sep.
PathCrawler::~PathCrawler ()
Definition at line 33 of file path_crawler.cpp.
References components.
Member Function Documentation
string PathCrawler::get_rel_path () [inline]
returns the relative path to a query, or a combination of queries
Definition at line 50 of file path_crawler.hpp.
References rel_path.
Referenced by hybfs_getattr().
string PathCrawler::get_first_path () [inline]
returns the path component from a query, only if it's specified as the first element
Definition at line 56 of file path_crawler.hpp.
References first_path.
Referenced by hybfs_getattr(), and hybfs_rename().
int PathCrawler::is_real () [inline]
returns 1 if the path component starts with REAL_DIR
Definition at line 61 of file path_crawler.hpp.
References first_path, and REAL_DIR.
Referenced by hybfs_getattr().
string PathCrawler::get_next ()
returns the next component from the path, separated by "/" It begins from the end to the begining.
Definition at line 43 of file path_crawler.cpp.
References found, last, rest, and sep.
Referenced by HybfsData::parse_branches().
int PathCrawler::has_next ()
returns 1 if there are still unprocessed elements
Definition at line 38 of file path_crawler.cpp.
References found, and rest.
Referenced by HybfsData::parse_branches().
int PathCrawler::break_queries ()
parse the path and adds to the component list the queries separated by '/(' and ')/' or '/(' and ')' if is the last element
Definition at line 59 of file path_crawler.cpp.
References components, DBG_PRINT, first_path, path, and rel_path.
Referenced by hybfs_getattr(), hybfs_rename(), and VirtualDirectory::vdir_readdir().
string PathCrawler::pop_next_query ()
gets the next query from the list of components
Definition at line 109 of file path_crawler.cpp.
References components.
Referenced by hybfs_rename(), and VirtualDirectory::vdir_readdir().
int PathCrawler::has_next_query ()
returns 1 if there are still elements in the list
Definition at line 119 of file path_crawler.cpp.
References components.
Referenced by hybfs_rename(), and VirtualDirectory::vdir_readdir().
Member Data Documentation
string PathCrawler::path [private]
Definition at line 24 of file path_crawler.hpp.
Referenced by break_queries(), and PathCrawler().
size_t PathCrawler::found [private]
Definition at line 25 of file path_crawler.hpp.
Referenced by get_next(), has_next(), and PathCrawler().
string PathCrawler::last [private]
Definition at line 27 of file path_crawler.hpp.
Referenced by get_next().
string PathCrawler::rest [private]
Definition at line 28 of file path_crawler.hpp.
Referenced by get_next(), has_next(), and PathCrawler().
char PathCrawler::sep [private]
Definition at line 30 of file path_crawler.hpp.
Referenced by get_next(), and PathCrawler().
string PathCrawler::rel_path [private]
the path that follows a query
Definition at line 34 of file path_crawler.hpp.
Referenced by break_queries(), and get_rel_path().
string PathCrawler::first_path [private]
the path that is the first component of a query
Definition at line 38 of file path_crawler.hpp.
Referenced by break_queries(), get_first_path(), and is_real().
list<string> PathCrawler::components [private]
Definition at line 40 of file path_crawler.hpp.
Referenced by break_queries(), has_next_query(), pop_next_query(), and ~PathCrawler().
The documentation for this class was generated from the following files:
include/path_crawler.hpp
hybfs-core/path_crawler.cpp