Hybfs: VirtualDirectory Class Reference
VirtualDirectory Class Reference
#include <virtualdir.hpp>
Public Member Functions
VirtualDirectory (const char *path)
~VirtualDirectory ()
int init ()
int vdir_validate (const char *path, int *flags)
int vdir_add_tag (vector< string > *tags, file_info_t *finfo)
int vdir_list_root (void *buf, fuse_fill_dir_t filler)
int vdir_readdir (const char *query, void *buf, fuse_fill_dir_t filler)
int vdir_replace (const char *oldq, const char *newq)
Private Attributes
DbBackend * db
Detailed Description
Definition at line 20 of file virtualdir.hpp.
Constructor & Destructor Documentation
VirtualDirectory::VirtualDirectory (const char * path)
Definition at line 32 of file virtualdir.cpp.
References db.
VirtualDirectory::~VirtualDirectory ()
Definition at line 37 of file virtualdir.cpp.
References db.
Member Function Documentation
int VirtualDirectory::init () [inline]
Definition at line 32 of file virtualdir.hpp.
References db, and DbBackend::db_init_storage().
int VirtualDirectory::vdir_validate (const char * path, int * flags)
int VirtualDirectory::vdir_add_tag (vector< string > * tags, file_info_t * finfo)
Definition at line 42 of file virtualdir.cpp.
References db, DbBackend::db_add_file_info(), and file_info_t::mode.
int VirtualDirectory::vdir_list_root (void * buf, fuse_fill_dir_t filler)
Definition at line 78 of file virtualdir.cpp.
References db, DbBackend::db_get_tags(), DbBackend::db_get_tags_values(), fill_buf(), and PRINT_ERROR.
int VirtualDirectory::vdir_readdir (const char * query, void * buf, fuse_fill_dir_t filler)
Definition at line 113 of file virtualdir.cpp.
References PathCrawler::break_queries(), db, DbBackend::db_get_filesinfo(), DBG_PRINT, PathCrawler::has_next_query(), PathCrawler::pop_next_query(), PRINT_ERROR, and REAL_DIR.
int VirtualDirectory::vdir_replace (const char * oldq, const char * newq)
Definition at line 57 of file virtualdir.cpp.
Member Data Documentation
DbBackend* VirtualDirectory::db [private]
Definition at line 22 of file virtualdir.hpp.
Referenced by init(), vdir_add_tag(), vdir_list_root(), vdir_readdir(), VirtualDirectory(), and ~VirtualDirectory().
The documentation for this class was generated from the following files:
include/virtualdir.hpp
hybfs-core/virtualdir.cpp