Hybfs: HybfsData Class Reference
HybfsData Class Reference
#include <hybfs_data.hpp>
Public Member Functions
HybfsData (char *mountp)
~HybfsData ()
int add_branch (const char *path)
int delete_branch (const char *path)
int parse_branches (const char *arg)
const char * get_branch_path (int brid)
int get_nbranches ()
int start_db_storage ()
int get_nlinks ()
int virtual_readdir (const char *query, void *buf, filler_t filler)
int virtual_addtag (const char *tag, const char *path)
int virtual_replace_query (const char *oldq, const char *newq, int brid)
Public Attributes
int doexit
int retval
Private Attributes
char * mountp
vector< string > branches
vector< VirtualDirectory * > vdirs
Detailed Description
Definition at line 26 of file hybfs_data.hpp.
Constructor & Destructor Documentation
HybfsData::HybfsData (char * mountp)
Definition at line 24 of file hybfs_data.cpp.
References doexit, mountp, and retval.
HybfsData::~HybfsData ()
Definition at line 272 of file hybfs_data.cpp.
References branches, PRINT_ERROR, and vdirs.
Member Function Documentation
int HybfsData::add_branch (const char * path)
Adds a branch to the overlaid list
Definition at line 31 of file hybfs_data.cpp.
References branches, DBG_PRINT, MAINDB, make_absolute(), METADIR, PRINT_ERROR, and vdirs.
Referenced by parse_branches().
int HybfsData::delete_branch (const char * path)
Deletes a branch from the list
Definition at line 84 of file hybfs_data.cpp.
References branches, PRINT_ERROR, and vdirs.
int HybfsData::parse_branches (const char * arg)
Parses the mount options and adds the branches
Definition at line 108 of file hybfs_data.cpp.
References ABORT, add_branch(), branches, PathCrawler::get_next(), PathCrawler::has_next(), and ROOT_SEP.
Referenced by hybfs_opts().
const char * HybfsData::get_branch_path (int brid)
Returns the branch path
Definition at line 129 of file hybfs_data.cpp.
References branches.
Referenced by hybfs_readdir(), and resolve_path().
int HybfsData::get_nbranches () [inline]
Returns the number of branches
Definition at line 69 of file hybfs_data.hpp.
References branches.
Referenced by hybfs_readdir().
int HybfsData::start_db_storage ()
Starts the databases
Definition at line 259 of file hybfs_data.cpp.
References vdirs.
int HybfsData::get_nlinks ()
Get the number of links from under us
Definition at line 137 of file hybfs_data.cpp.
References branches.
Referenced by fill_root(), and hybfs_getattr().
int HybfsData::virtual_readdir (const char * query, void * buf, filler_t filler)
virtual readdir for each branch that we have
Definition at line 158 of file hybfs_data.cpp.
References vdirs.
Referenced by fill_root(), and hybfs_readdir().
int HybfsData::virtual_addtag (const char * tag, const char * path)
Adds a tag for this path to the corresponding db. The path is relative and it will be changed to absolute here.
Definition at line 181 of file hybfs_data.cpp.
References DBG_PRINT, file_info_t::fid, file_info_t::mode, file_info_t::name, file_info_t::namelen, resolve_path(), and vdirs.
Referenced by hybfs_rename().
int HybfsData::virtual_replace_query (const char * oldq, const char * newq, int brid)
This is a sort of rename/move but for tags. It can also change the path of a file from a database, since it is seen as a special value of the tag 'path:'
Definition at line 254 of file hybfs_data.cpp.
References vdirs.
Referenced by normal_rename().
Member Data Documentation
char* HybfsData::mountp [private]
the mount directory - not used (yet)
Definition at line 32 of file hybfs_data.hpp.
Referenced by HybfsData().
vector<string> HybfsData::branches [private]
branch paths
Definition at line 36 of file hybfs_data.hpp.
Referenced by add_branch(), delete_branch(), get_branch_path(), get_nbranches(), get_nlinks(), parse_branches(), and ~HybfsData().
vector<VirtualDirectory *> HybfsData::vdirs [private]
database handle for each branch
Definition at line 40 of file hybfs_data.hpp.
Referenced by add_branch(), delete_branch(), start_db_storage(), virtual_addtag(), virtual_readdir(), virtual_replace_query(), and ~HybfsData().
int HybfsData::doexit
does fuse need to exit? Set this to 1 if yes.
Definition at line 101 of file hybfs_data.hpp.
Referenced by hybfs_opts(), and HybfsData().
int HybfsData::retval
the return value at exit
Definition at line 106 of file hybfs_data.hpp.
Referenced by hybfs_opts(), and HybfsData().
The documentation for this class was generated from the following files:
include/hybfs_data.hpp
hybfs-core/hybfs_data.cpp