Hybfs: hybfs-core/fileops.cpp File Reference
hybfs-core/fileops.cpp File Reference
#include <unistd.h>
#include <fcntl.h>
#include <string.h>
#include "hybfs.h"
#include "misc.h"
#include "hybfsdef.h"
#include "path_crawler.hpp"
Functions
static int normal_rename (HybfsData *data, const char *from, const char *to, int rootlen)
int hybfs_rename (const char *from, const char *to)
int hybfs_unlink (const char *path)
Function Documentation
int hybfs_rename (const char * from, const char * to)
Definition at line 64 of file fileops.cpp.
References PathCrawler::break_queries(), DBG_PRINT, DBG_SHOWFC, get_data(), PathCrawler::get_first_path(), PathCrawler::has_next_query(), IS_ROOT, normal_rename(), PathCrawler::pop_next_query(), REAL_DIR, and HybfsData::virtual_addtag().
Referenced by main().
int hybfs_unlink (const char * path)
Definition at line 139 of file fileops.cpp.
References DBG_SHOWFC, get_data(), and resolve_path().
Referenced by main().
static int normal_rename (HybfsData * data, const char * from, const char * to, int rootlen) [static]
Definition at line 32 of file fileops.cpp.
References DBG_SHOWFC, PRINT_ERROR, resolve_path(), and HybfsData::virtual_replace_query().
Referenced by hybfs_rename().