Hybfs: include/hybfs.h File Reference
include/hybfs.h File Reference
#include <fuse.h>
#include <dirent.h>
#include <errno.h>
#include <stdio.h>
#include "hybfsdef.h"
#include "hybfs_data.hpp"
Defines
#define DBG_PRINT(...)
#define DBG_SHOWFC()
#define PRINT_ERROR(...) fprintf(stderr, __VA_ARGS__);
#define ABORT(cond, message)
#define IS_ROOT(path)
Functions
HybfsData * get_data ()
int hybfs_rename (const char *from, const char *to)
int hybfs_unlink (const char *path)
int hybfs_mkdir (const char *path, mode_t mode)
int hybfs_rmdir (const char *path)
int hybfs_readdir (const char *path, void *buf, fuse_fill_dir_t filler, off_t offset, struct fuse_file_info *fi)
int hybfs_getattr (const char *path, struct stat *stbuf)
int hybfs_access (const char *path, int mask)
Define Documentation
#define ABORT (cond, message)
Value:
if(cond) { fprintf(stderr, "Abort from function %s : %s\n",__func__,message); \
        exit(1); }
Definition at line 52 of file hybfs.h.
Referenced by make_absolute(), and HybfsData::parse_branches().
#define DBG_PRINT (...)
Definition at line 45 of file hybfs.h.
Referenced by HybfsData::add_branch(), PathCrawler::break_queries(), DbBackend::create_main_tables(), DbBackend::db_check_tag(), DbBackend::db_get_files(), DbBackend::db_get_filesinfo(), DbBackend::db_init_storage(), hybfs_getattr(), hybfs_opts(), hybfs_readdir(), hybfs_rename(), make_absolute(), normal_getattr(), normal_readdir(), VirtualDirectory::vdir_readdir(), and HybfsData::virtual_addtag().
#define DBG_SHOWFC ()
Definition at line 46 of file hybfs.h.
Referenced by DbBackend::db_add_file(), DbBackend::db_add_file_info(), DbBackend::db_add_tag(), DbBackend::db_check_tag(), DbBackend::db_close_storage(), DbBackend::db_get_tags(), DbBackend::db_get_tags_values(), DbBackend::db_init_storage(), hybfs_access(), hybfs_getattr(), hybfs_mkdir(), hybfs_rename(), hybfs_rmdir(), hybfs_unlink(), and normal_rename().
#define IS_ROOT (path)
Value:
((strcmp(path, REAL_DIR) == 0 || (strncmp(path, REAL_DIR, strlen(REAL_DIR) -1) == 0 \
                && strlen(path) == strlen(REAL_DIR) -1)) ? 1 : 0)
Definition at line 56 of file hybfs.h.
Referenced by hybfs_rename().
#define PRINT_ERROR (...) fprintf(stderr, __VA_ARGS__);
Definition at line 50 of file hybfs.h.
Referenced by HybfsData::add_branch(), DbBackend::db_get_tags(), DbBackend::db_get_tags_values(), HybfsData::delete_branch(), hybfs_access(), normal_rename(), VirtualDirectory::vdir_list_root(), VirtualDirectory::vdir_readdir(), and HybfsData::~HybfsData().
Function Documentation
HybfsData* get_data () [inline]
Definition at line 62 of file hybfs.h.
Referenced by hybfs_access(), hybfs_getattr(), hybfs_readdir(), hybfs_rename(), and hybfs_unlink().
int hybfs_access (const char * path, int mask)
Definition at line 125 of file stats.cpp.
References DBG_SHOWFC, get_data(), HAS_PATH, PRINT_ERROR, REAL_DIR, and resolve_path().
Referenced by main().
int hybfs_getattr (const char * path, struct stat * stbuf)
Definition at line 50 of file stats.cpp.
References PathCrawler::break_queries(), DBG_PRINT, DBG_SHOWFC, get_data(), PathCrawler::get_first_path(), HybfsData::get_nlinks(), PathCrawler::get_rel_path(), PathCrawler::is_real(), normal_getattr(), REAL_DIR, and resolve_path().
Referenced by main().
int hybfs_mkdir (const char * path, mode_t mode)
Definition at line 15 of file dirops.cpp.
References DBG_SHOWFC.
int hybfs_readdir (const char * path, void * buf, fuse_fill_dir_t filler, off_t offset, struct fuse_file_info * fi)
Definition at line 68 of file readdir.cpp.
References DBG_PRINT, fill_root(), HybfsData::get_branch_path(), get_data(), HybfsData::get_nbranches(), normal_readdir(), REAL_DIR, resolve_path(), and HybfsData::virtual_readdir().
Referenced by main().
int hybfs_rename (const char * from, const char * to)
Definition at line 64 of file fileops.cpp.
References PathCrawler::break_queries(), DBG_PRINT, DBG_SHOWFC, get_data(), PathCrawler::get_first_path(), PathCrawler::has_next_query(), IS_ROOT, normal_rename(), PathCrawler::pop_next_query(), REAL_DIR, and HybfsData::virtual_addtag().
Referenced by main().
int hybfs_rmdir (const char * path)
Definition at line 28 of file dirops.cpp.
References DBG_SHOWFC.
int hybfs_unlink (const char * path)
Definition at line 139 of file fileops.cpp.
References DBG_SHOWFC, get_data(), and resolve_path().
Referenced by main().