Hybfs: hybfs-core/readdir.cpp File Reference
hybfs-core/readdir.cpp File Reference
#include <string.h>
#include "hybfs.h"
#include "misc.h"
Functions
static int normal_readdir (const char *path, void *buf, fuse_fill_dir_t filler)
static int fill_root (HybfsData *hybfs_core, void *buf, filler_t filler)
int hybfs_readdir (const char *path, void *buf, fuse_fill_dir_t filler, off_t offset, struct fuse_file_info *fi)
Function Documentation
static int fill_root (HybfsData * hybfs_core, void * buf, filler_t filler) [inline, static]
Definition at line 47 of file readdir.cpp.
References HybfsData::get_nlinks(), REAL_DIR, and HybfsData::virtual_readdir().
Referenced by hybfs_readdir().
int hybfs_readdir (const char * path, void * buf, fuse_fill_dir_t filler, off_t offset, struct fuse_file_info * fi)
Definition at line 68 of file readdir.cpp.
References DBG_PRINT, fill_root(), HybfsData::get_branch_path(), get_data(), HybfsData::get_nbranches(), normal_readdir(), REAL_DIR, resolve_path(), and HybfsData::virtual_readdir().
Referenced by main().
static int normal_readdir (const char * path, void * buf, fuse_fill_dir_t filler) [inline, static]
Definition at line 17 of file readdir.cpp.
References DBG_PRINT.
Referenced by hybfs_readdir().