Hybfs: hybfs-core/stats.cpp File Reference
hybfs-core/stats.cpp File Reference
#include <string>
#include <sys/time.h>
#include <unistd.h>
#include <fcntl.h>
#include <string.h>
#include <assert.h>
#include "hybfs.h"
#include "misc.h"
#include "path_crawler.hpp"
Functions
static int normal_getattr (HybfsData *data, const char *path, struct stat *stbuf)
int hybfs_getattr (const char *path, struct stat *stbuf)
int hybfs_access (const char *path, int mask)
Function Documentation
int hybfs_access (const char * path, int mask)
Definition at line 125 of file stats.cpp.
References DBG_SHOWFC, get_data(), HAS_PATH, PRINT_ERROR, REAL_DIR, and resolve_path().
Referenced by main().
int hybfs_getattr (const char * path, struct stat * stbuf)
Definition at line 50 of file stats.cpp.
References PathCrawler::break_queries(), DBG_PRINT, DBG_SHOWFC, get_data(), PathCrawler::get_first_path(), HybfsData::get_nlinks(), PathCrawler::get_rel_path(), PathCrawler::is_real(), normal_getattr(), REAL_DIR, and resolve_path().
Referenced by main().
static int normal_getattr (HybfsData * data, const char * path, struct stat * stbuf) [inline, static]
Definition at line 29 of file stats.cpp.
References DBG_PRINT, REAL_DIR, and resolve_path().
Referenced by hybfs_getattr().